# Development Configuration
version: "0.1.0"
environment: "development"
log_level: "debug"

server:
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "30s"
  grpc:
    port: 9090

database:
  url: "postgres://localhost:5432/dce_dev?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

redis:
  url: "localhost:6379"
  password: ""
  db: 0

kafka:
  brokers: ["localhost:9092"]
  group_id: "dce-backend"

telephony:
  sip_proxy: "sip.example.com:5060"
  stun_servers: 
    - "stun:stun.l.google.com:19302"
    - "stun:stun1.l.google.com:19302"

compliance:
  tcpa_enabled: true
  gdpr_enabled: true
  allowed_timezones:
    - "America/New_York"
    - "America/Chicago" 
    - "America/Denver"
    - "America/Los_Angeles"

consent:
  cache_ttl: "1h"
  check_timeout: "2s"
  batch_size: 100
  retention_days: 2555  # 7 years for TCPA compliance
  proof_storage:
    provider: "s3"
    bucket: "dce-consent-proofs"
    encryption: true
  performance:
    target_latency_ms: 2
    cache_hit_ratio_target: 0.95
  features:
    parallel_processing: true
    real_time_events: true
    audit_logging: true

security:
  jwt_secret: "your-jwt-secret-change-in-production"
  token_expiry: "24h"
  rate_limit:
    requests_per_second: 100
    burst_size: 200